### ISSUE TITLE
hi, please help me on how i can create tenants on hyku application.

### ISSUE THREAD

**Issue by eddamalique01** [samvera/hyku#1473]
### Descriptive summary

Include what version of Hyku relates to this issue (0.x, 1.x, HEAD, etc.) if appropriate, and any relevant tracebacks if you're reporting a bug.

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by aprilrieger** [comment]
Hi eddamalique01,

Please refer to this section of the wiki where it describes how to create a new tenant: https://github.com/samvera/hyku/wiki/Managing-who-can-create-new-tenants

If you have any additional questions please feel free to @ me here and I will respond and help guide you through.

Sincerely,
April Rieger
