### ISSUE TITLE
Bulk import 

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyku#1474]
The ability to perform content ingest in Hyku through an automated process is necessary for data migrations. HykuDirect Pilots mentioned this need specifically.  Relevant  for CONTENTdm, Digital Commons, and DSpace migrations. Not necessarily relevant to local Hyku or Hyrax migrations (that can be done via database (DB) dump and reindex).

**Comment by KihOshk** [comment]
I'm attempting to migrate a bunch of CDM content and am a bit confused as to why this feature isn't apparent in Hyrax. Did you have any luck here Hannah?

**Comment by CCMumma** [comment]
Indicated as a requirement for the Texas Digital Library Hyku pilot (February-July 2018) partners.

**Comment by crocken** [comment]
@KihOshk hey john!  what are you using to pull content out of CDM? are you part of the #hydra-migrations channel on samvera?  theres a pretty good lil community of ppl doing cdm-to-hyrax/hyku there.

**Comment by KihOshk** [comment]
@crocken Howdy Todd! Thanks for the advice; I'll have a look. Currently, I'm using some really ugly Python I cobbled together which extracts metadata field-names and their data from the CDM collections' desc.all files and dumps it into some MySQL tables. Incidentally, although I've been coding for decades, I'm JUST THIS MORNING screwing around with integrating GitHub with VS Code. I'll post that project if you're interested. Thanks again; I';ll check out #hydra-migrations this afternoon.

**Comment by crocken** [comment]
University of Houston is working on a migration grant for CDM-to-Hyku (https://bridge2hyku.github.io/),  if you have any non-technical people working with you, have them check out our new cdm-bridge:    https://github.com/Bridge2Hyku/cdm-bridge for easy mapping of metdata out of cdm.
