### ISSUE TITLE
Verify uploaded files are multitenant-aware

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyku#149]
Check where `UploadedFiles` live on the filesystem, and also where CarrierWave puts things (like user avatars) and make sure we won't run into conflicts.

**Comment by cbeer** [comment]
> @mjgiarlo: i’m guessing carrierwave will be a problem (although perhaps not catastrophic.. you’d have to share a database id and filename), but it looks like we can do a per-tenant storage dir (https://github.com/carrierwaveuploader/carrierwave#changing-the-storage-directory) or push files directly to S3 (https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3).

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> This will likely require changes in Sufia, so we could consider generating the uploader into app or some sort of config proc.

**Comment by orangewolf** [comment]
this is done
