### ISSUE TITLE
Remove peek

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyku#1565]
The atomic gem is deprecated. This is a transitive dependency of peek-redis and peek-faraday.  Neither of these gems have seen updates in a few years and appear abandoned.  Unless anyone really needs these features, we should consider removing them.

**Comment by orangewolf** [comment]
I agree with this. We've run in to quite a few peek related issues lately and it doesn't seem like the tool has a clear path forward

**Comment by orangewolf** [comment]
I have a branch for this I can open a PR. could @geekscruff and @cldambrosio weight in if they are using this feature please?

**Comment by geekscruff** [comment]
We're not using peek, +1 to this.
