### ISSUE TITLE
DNS broken for multitenant - "This site can’t be reached" : dory? hosts file? or...?

### ISSUE THREAD

**Issue by tedstrauss** [samvera/hyku#1595]
### Descriptive summary

Hyku installed at commit: `768216d24bb0eff4c04b7f5d40f941cf9217e653` (Aug 29, 2019)

### Rationale

- I am running hyku using the docker-compose install method. 
- I am using dory. 
- Hyku boots up fine. 
- I am able to create a new tenant ("account") as a superadmin in the hyku interface. 
- When I open the tenant page ("tenant1.domain.com") it fails with "This site can’t be reached". 
- It seems very likely to be a DNS issue, so Dory is not working as it's supposed to?
 
So, my question is: how do I get dory to work? 
Do I need to update `/etc/hosts`? 
The hosts file contains two lines: 

```
127.0.1.1 hyku-02 hyku-02
127.0.0.1 localhost
```

My `config/settings.yml` contains:

```
multitenancy:
  enabled: true
  default_host: # "%{tenant}.mydomain.com"
  admin_host: mydomain.com
  admin_only_tenant_creation: false
```

My docker-compose.yml and docker-compose.production.yml contains:

```
      - SETTINGS__MULTITENANCY__ADMIN_HOST=mydomain.com
      - SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION=true
      - SETTINGS__MULTITENANCY__DEFAULT_HOST=%{tenant}.mydomain.com
      - SETTINGS__MULTITENANCY__ENABLED=true
```

### Expected behavior

After creating a new account/tenant called `tenant-name` the sub-domain `tenant-name.mydomain.com` should load a fresh repository. 

### Actual behavior

"This site can’t be reached" error page when browser points to `tenant-name.mydomain.com` 

### Steps to reproduce the behavior

- Activate  dory. 
- Install and start Hyku using the docker-compose install method.
- Setup config files as shown above (based on wiki documentation). 
- Create and login as superadmin user. 
- Create new tenant/account called `tenant-name`. 
- Point browser at `tenant-name.mydomain.com`.

### Related work

https://github.com/samvera/hyku/issues/1139
https://github.com/samvera/hyku/wiki/Multi-tenant-domain-model

**Comment by dlim87** [comment]
Try adding `SETTINGS__MULTITENANCY__ROOT_HOST=mydomain.com`
