### ISSUE TITLE
Remove chart directory from code coverage 

### ISSUE THREAD

**Issue by orangewolf** [samvera/hyku#1615]
### Descriptive summary

Remove the chart directory from coveralls code coverage calculation. 

### Rationale

We don’t currently have specs set up for helm charts and it is counting against us every time we edit them. 

### Expected behavior

Code coverage number does not count helm chart files. 

### Actual behavior

Code coverage goes down every time an edit is made

**Comment by cjcolvar** [comment]
@orangewolf Is this issue still relevant? I don't see `/chart` in the Coveralls reporting for recent builds (only `/app` and `/lib` seem to be covered).

**Comment by orangewolf** [comment]
I agree, this appears fixed.
