### ISSUE TITLE
Hyku 2.1 doesn't support Ruby 2.7

### ISSUE THREAD

**Issue by cjcolvar** [samvera/hyku#1630]
### Descriptive summary

Ruby 2.7 breaks Hyku due to the version of config being used (1.5.1) doesn't support it (see https://github.com/rubyconfig/config/issues/259).  When I go to upgrade config I'm blocked by a dependency version conflict between hyrax and config :
```
$ bundle update --conservative config
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.....
Bundler could not find compatible versions for gem "dry-validation":
  In snapshot (Gemfile.lock):
    dry-validation (= 0.10.7)
  In Gemfile:
    config (~> 2.2, >= 2.2.1) was resolved to 2.2.1, which depends on
      dry-validation (>= 1.0.0, ~> 1.0)
    hyrax (~> 2.5) was resolved to 2.5.1, which depends on
      dry-validation (~> 0.9)
```
FWIW It looks like latest Hyrax 2.x hasn't changed its dry-validation dependency.  On its own Hyrax 2.x supports ruby 2.7: https://github.com/samvera/hyrax/pull/4376

**Comment by orangewolf** [comment]
@cjcolvar I believe this can be closed now?

**Comment by cjcolvar** [comment]
:+1: Yup, thanks for checking!
