### ISSUE TITLE
Work show page - undefined method "to_h" for Hyrax::FileSetPresenter (SharedSearchHelper)

### ISSUE THREAD

**Issue by bkiahstroud** [samvera/hyku#1857]
### Descriptive summary

Version: `HEAD@e2f508f` 

When navigating to a work's show page that has a `FileSet`, the following error is thrown: 

```
undefined method `to_h' for #<Hyrax::FileSetPresenter:0x0000004017d9e7c8>
```

<details><summary>Stack trace (partial)</summary>

```
app/helpers/shared_search_helper.rb:6:in `generate_work_url'
app/helpers/blacklight/blacklight_helper_behavior.rb:409:in `link_to_document'
blacklight (6.24.0) app/helpers/blacklight/catalog_helper_behavior.rb:224:in `render_thumbnail_tag'
hyrax (3.4.2) app/views/hyrax/base/_member.html.erb:3:in `__usr_local_bundle_gems_hyrax_______app_views_hyrax_base__member_html_erb___3883904219280646656_1206420'
```

</details>

### Steps to reproduce the behavior

1. Login as an admin 
2. Navigate to Dashboard > Works > Add New Work 
3. Select any work type. Fill out the required fields, including uploading a file 
4. Click "Save". You will be redirected to the work's show page 
5. Wait ~1 minute for the file to be processed in the background 
6. Refresh the page 
7. Observe the error 

### Related work

#1801 is the last time `SharedSearchHelper#generate_work_url` was touched

**Comment by bkiahstroud** [comment]
Paraphrased suggestion from @laritakr -- 

`SharedSearchHelper#generate_work_url` expects a solr document. Figure out how to ensure that's what is being sent by `app/helpers/blacklight/blacklight_helper_behavior.rb:409:in 'link_to_document'` (instead of the `FileSetPresenter`)

**Comment by laritakr** [comment]
The only other thing that came to mind was the work that you noted as the last time it was touched. The `generate_work_url` method checks and returns if it’s not a shared tenant. You wouldn’t be adding a work in a shared tenant, so why does it not return before the failed line?

**Comment by bkiahstroud** [comment]
@laritakr it looks like that check has [since been removed](https://github.com/samvera/hyku/commit/43f5d9425a966e229be4d96f3230a54d11092dde#diff-ef13b16240ca4675e4fbbca10e6d9589d817f73f989e0f180e7293d19fe04290L5)

**Comment by bkiahstroud** [comment]
@laritakr do you remember why you removed it?

**Comment by laritakr** [comment]
@bkiahstroud I don't remember offhand... there were a lot of url-related bugs with the shared search tenant. 

But the change to fix the bug above [is in utk here](https://github.com/scientist-softserv/utk-hyku/blob/main/app/helpers/blacklight/blacklight_helper_behavior.rb#L410).
