### ISSUE TITLE
README improvements for running locally

### ISSUE THREAD

**Issue by bkiahstroud** [samvera/hyku#1920]
## Summary

Hyku v5 / `HEAD` 

A couple improvements could be made to the README to make it easier for people who are spinning the app up locally for the first time. Specifically: 

- Instructions on configuring Dory's config file to support the .test tld 
- Username and password for the HTTP basic auth that is in front of private tenants 

### Dory .test tld

Currently, the instructions for this simply link to [Dory's README](https://github.com/FreedomBen/dory#config-file), which has instructions for how to setup a default dory config file, but not for how to support the .test tld. This can be misleading 

### HTTP basic auth 

Since tenants are private by default, most people spinning the app up locally will hit this barrier. No documentation for this currently exists in the README. An explanation should be added, along with the default values for the username and password.

**Comment by adamhgriffith-uofu** [comment]
Seconded on the HTTP basic auth piece.

**Comment by adamhgriffith-uofu** [comment]
Found the HTTP basic auth credentials in `./app/controllers/application_controller.rb`.
```ruby
# Extra authentication for palni-palci during development phase
    def authenticate_if_needed
      # Disable this extra authentication in test mode
      return true if Rails.env.test?
      if (is_hidden || is_staging) && !is_api_or_pdf
        authenticate_or_request_with_http_basic do |username, password|
          username == "samvera" && password == "hyku"
        end
      end
    end
```
