### ISSUE TITLE
Hyku installation on local Desktop Docker

### ISSUE THREAD

**Issue by teoflax** [samvera/hyku#1981]
### Descriptive summary

I have started to do tests on installing Hyku in my local machine, but I cannot find the test user account so that I can do the demo testing. I used instructions on this page https://github.com/samvera/hyku  . Please assist.

Include what version of Hyku relates to this issue (0.x, 1.x, HEAD, etc.) if appropriate, and any relevant tracebacks if you're reporting a bug.

### Rationale
I'm tasked to install samvera as it is the solution identified by the library management to replace the legacy repository system for the consortium universities.

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Expected behavior
Login and be able to test how the system actually works
### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by adamhgriffith-uofu** [comment]
If your local machine isn't Linux, using the following from `./.env` should get you started:
```
INITIAL_ADMIN_EMAIL=admin@example.com
INITIAL_ADMIN_PASSWORD=testing123
```

**Comment by adamhgriffith-uofu** [comment]
And in [#1920](https://github.com/samvera/hyku/issues/1920#issuecomment-1720042295), I found the development "HTTP basic auth credentials" to be:
```
Username: samvera
Password: hyku
```

Hope this helps.

**Comment by teoflax** [comment]
Thanks @adamhgriffith-uofu
