### ISSUE TITLE
:bug: Can't watch feature specs in chrome.hyku.test

### ISSUE THREAD

**Issue by ShanaLMoore** [samvera/hyku#2057]
### Descriptive summary
 
The chrome service in docker-compose.yml may need some updates. From the latest hyku, when I run feature specs I can connect to chrome.hyku.test but nothing displays. 

### Rationale

It's a lot easier fix tests when you can see them run. 

### Expected behavior

chrome.hyku.test will display the browser of the features specs as they run

### Actual behavior

unable to see tests run

### Steps to reproduce the behavior

docker compose up -d && docker compose exec web bash
in a browser connect to chrome.hyku.test and enter the password if prompted
bundle exec rspec spec/features

I'd expect to see the tests display the browser it's testing with in chromel.hyku.test

### Related work

This may be helpful, however when I time boxed it, I was still unsuccessful.

https://github.com/scientist-softserv/palni-palci/commit/3511c594e7a8e3d7acfabf032bcc3f19c49fe5ac

**Comment by laritakr** [comment]
Appears to be working (but need to turn on js: true on spec)
