### ISSUE TITLE
Documentation regarding versioning/upgrading/tagging

### ISSUE THREAD

**Issue by ryan-lang** [samvera/hyku#2142]
### Descriptive summary

I've been trying to get a test instance of the hyku stack running on my local machine, and there's been significant confusion over which version of the codebase I need to be running.

As a developer naive to this project, I read the "Running the stack" documentation, and assume I can `git clone` followed by `docker compose up` and be on my way.  

However, this results in running an old docker image against a fresh git repo.  It will pull the docker image tagged `:latest`, which, as of this writing, is about 1.5 months behind HEAD.  In my case, I run into a Ruby version mismatch, however this is irrelevant -- any number of things could go wrong in this scenario.

### Rationale

The spirit of the "Running the stack" documentation is to allow someone to get a test instance running quickly. Therefore some documentation is needed to clarify how to correctly match the codebase version to the docker version.

### Expected behavior

There are several possible paths to take:

1) Instruct the user to clone the latest release, possibly introducing a new `stable` tag. There will be a maintainer responsibility to keep git `stable` in sync with docker `:latest.` Also document how the user can run the bleeding-edge if they so choose, by specifying the TAG env var when running `docker compose up`.

2) Instruct the user to `docker compose build` prior to `docker compose up.` I'm not a docker expert, but it appears this would rebuild the image using the current codebase. However, this could cause confusion if the user ever `docker compose pull`, because that will pull the wrong image again.

3) Explicitly state the correct version of the image in docker-compose.yml instead of using `:latest` -- this is probably impractical and error-prone, unless it can be automated.

**EDIT:** The documentation should also cover upgrading, which will largely overlap with what I've already described.

### Actual behavior

There is no documentation to this effect.

FWIW, I'd be happy to offer a pull request, but please point me in the right direction on how the maintainers would like to handle this.

**Comment by jeremyf** [comment]
@ryan-lang As someone regularly working on Hyku, I would welcome documentation.

The nature of Hyku at present is most likely to follow on step 2 (`docker compose build`).  We're actively working on Hyku v6 with Hyrax 5 and Rails 6 upgrades.  We're also working on what we've called [Knapsack](https://github.com/samvera-labs/hyku_knapsack), a mechanism for isolating changes in your local Hyku instance from the Hyku application (thus hopefully easing the maintenance burden).

What I often do is:

- `docker compose build`
- `docker compose up`

But the wooly nature of Hyku as an App that folks then fork and make their changes means that a `stable` version is hard to pin down.  Your best bet for "stability" is to target tagged versions; as those are "released".
