### ISSUE TITLE
Heading Text Is Partially Hidden by Search Box

### ISSUE THREAD

**Issue by christhepianist** [samvera/hyku#2356]
### Descriptive summary

We are running Hyku version 6 with all main commits up to the latest, 69b3e60.

The header information in the Institutional Repository theme includes the word "Hyku" twice. The second time, the search box partially hides it. The first instance is a link (as it should be) and the second does not seem to linked.
![header](https://github.com/user-attachments/assets/f7b9335f-1ea3-49c9-9da8-d83dc8b32aed)

In version 5, you can see that even though you see both "Hyku" words, they are not partially hidden by the search box:
![header 3](https://github.com/user-attachments/assets/779a9035-78b6-492a-b92f-1287c00fa5b7)
![header 2](https://github.com/user-attachments/assets/c1adc1da-07a7-4753-a3fb-9928c5973bc3)

In version 5, I updated the Application Name in the Settings/Label section to "Hyku Revised" and see the name:
![header 4](https://github.com/user-attachments/assets/706a20e6-a20c-4e70-b595-5e588c7f19f8)
![header 5](https://github.com/user-attachments/assets/ec5b2438-8818-40bf-b0b7-beb22df0ce4e)

I did the same in version 6 and the words were still partially hidden:
![header 6](https://github.com/user-attachments/assets/ad4853ea-2068-4e89-80c9-11343a097f02)
![header 7](https://github.com/user-attachments/assets/24aecfba-4f91-4022-a379-7fd9e1524a96)

I added a logo to the repository and still the name is partially hidden:
![header 8](https://github.com/user-attachments/assets/7c7b6d60-6785-427c-8a9e-f29434dab609)

### Rationale

The header is one of the first items users see and to have it messy makes them question the service itself.

### Expected behavior

The word Hyku should only appear once. The second should be removed.

### Actual behavior

The word Hyku appears twice. The second is not linked and is partially hidden by the search box.

### Steps to reproduce the behavior

1. Open https://peterson2.demo6.hyku.amigos.org/?locale=en

### Related work

Link to related tickets or prior related work here.

**Comment by laritakr** [comment]
Changes made in the above commit reverts the title to the prior position, where it is centered between the logo and the search bar. 
Additionally, it removes the display of text if there is no logo to prevent the duplication.
