### ISSUE TITLE
On the Hyku vs. Hyrax page, it says "Hyku is build to support multi-tenancy to power the Hyku Direct service from Duraspace." Is there more information that can be added here about Duraspace? Should there be information added about other multi-tenant instances of Hyku that are available from organizations like Palni/Palci?

### ISSUE THREAD

**Issue by bkiahstroud** [samvera/hyku#2383]
https://samvera.atlassian.net/wiki/spaces/samvera/pages/2225111237/Hyku+vs+Hyrax

**Comment by orangewolf** [comment]
Duraspace hosting doesn't exist and should be removed. HykuUp is the only generally available version at the moment, but I'd defer to Heather as to her thoughts on how its best phrased. @heathergreerklein

**Comment by heathergreerklein** [comment]
I removed the outdated information and added a line with a link to the service provider index on the website.
