### ISSUE TITLE
db/schema.rb contains a work_authorizations table that does not have a corresponding migration

### ISSUE THREAD

**Issue by gleithner** [samvera/hyku#2388]
Version 6.0.0.920da19baa

I'm not sure whether this matters, but while experimenting with the schema and migrations, I noticed that when running db:create && db:migrations:reset and diffing the resulting schema.rb to the original schema.rb, that the only thing difference is that it is missing the work_authorizations table. I also noticed that the palni-palci repo has a migration that adds this table but the Hyku repo does not.

**Comment by orangewolf** [comment]
This table should not be in the schema at this time. It is part of a feature for cross library lending that exists in the PALNI / PALCI install and seems to have snuck in to the code. I'll open a PR to remove it

**Comment by orangewolf** [comment]
https://github.com/samvera/hyku/pull/2400
