### ISSUE TITLE
External controlled vocabularies (LCSH, MESH, TGN, etc.)

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyku#287]
As a repository admin who is configuring my repository though the UI, I need to enable/disable the use of external controlled vocabularies in the repository’s collections for select fields, such as LCSH or MESH for subject fields, or TGN for geographic place names, so that a depositor who is entering description for a deposit through the UI has the option of applying a controlled value.

**Comment by jcoyne** [comment]
Does this imply that we should be collecting linked data or only strings (it seems a shame not to do linked data)?  Should we constrain only to the values available in the external authority or allow free text in addition to what the authority provides.  Certain authorities, geonames for instance, also require credentials. Where should those go?

**Comment by jcoyne** [comment]
Should we be mirroring these authorities locally? What should happen if the remote authority becomes unresponsive?

**Comment by orangewolf** [comment]
this needs to be fully respected and tossed back on the roadmap by someone who wants this feature.
