### ISSUE TITLE
Locally controlled vocabularies

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyku#288]
As a repository admin who is configuring my repository though the UI, I need to enable/disable the use of locally controlled vocabularies in the repository’s collections for select fields, such as a list of academic department names to be available for entry in the creator or subject field, so that a depositor who is entering description for a deposit through the UI has the option of applying a controlled value.

**Comment by jcoyne** [comment]
Should there be a UI for a vocabulary manager like  https://github.com/OregonDigital/ControlledVocabularyManager ?  Is it okay to introduce a dependency on a triple store?  Can we use Blazegraph (has a licensing fee, I think)?

**Comment by orangewolf** [comment]
solved via DOT work in 2022
