### ISSUE TITLE
Repo admin can enable/disable Rightsstatements.org in collections

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyku#289]
As a repository admin who is configuring my repository though the UI, I need to enable/disable the use of Rightsstatements.org in the repository’s collections, so that a depositor who is entering description for a deposit through the UI has the option of applying standard rights statement.

**Comment by jcoyne** [comment]
What is "standard rights statement"?

**Comment by hannahfrost** [comment]
@jcoyne By "standard rights statement", I mean one of the 12 standardized options available from rightsstatements.org.

**Comment by jcoyne** [comment]
Why would you ever want to disable having 12 standard options available. What is the alternative?

**Comment by jcoyne** [comment]
What exactly do you mean by:
> the use of Rightsstatements.org

How would we use it?  Just copy the 12 options to our server?

**Comment by hannahfrost** [comment]
> Why would you ever want to disable having 12 standard options available. What is the alternative?

Rightsstatements.org is brand new. I only know of one institution that is starting to implement them.  The decision to implement them is likely made at a high level (above a repository admin), and requires related policy/decision making. HyBox should support them (and in doing so encourage their take-up), but not assume that everyone is ready to, or even wants to, implement. 

The alternative would be a non-standardized value in usual rights related fields (dc:rights or mods:accessCondition)

> How would we use it? Just copy the 12 options to our server?

According to the page on the site, "We recommend that institutions that are using the statements provided by RightsStatements.org do so by storing the URI of the rights statement in a metadata element or property associated with the cultural heritage object to which the rights statement applies. Examples of such fields include dc:rights or edm:rights."

**Comment by jcoyne** [comment]
> The alternative would be a non-standardized value in usual rights related fields (e.g., dc:rights or mods:accessCondition)

So, what would the non-standardized values be? What should show up in the site if you've disabled `Use rightstatements.org`
