### ISSUE TITLE
Add a rightsHolder field as "Rights Holder"

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyku#294]
- Required: no
- Repeatable: yes
- Values: Controlled values from viaf.org or string

Per https://dp.la/info/wp-content/uploads/2015/03/MAPv4.pdf (page 7)

**Comment by mjgiarlo** [comment]
Thanks for creating this issue, @hannahfrost. Have a few clarifying questions:

* Do we care what sorts of values go into this field, or how they're formatted?
* Should the field be required?
* Should the field be repeatable?

**Comment by jcoyne** [comment]
> Do we care what sorts of values go into this field, or how they're formatted?

They should be the rights statements URIs

> Should the field be required?

Yes.

> Should the field be repeatable?

According to the map v4 documentation, no. But Hanna's spreadsheet says yes.  My opinion is "no"

**Comment by mjgiarlo** [comment]
@jcoyne shouldn't the rights holder be an agent rather than a rights statement?

**Comment by jcoyne** [comment]
Ack. I was looking at `rights` not `rightsHolder`. I retract everything.

**Comment by hannahfrost** [comment]
@mjgiarlo Finished the ticket finally. I'm trying to help get DLPA MAPv4 work into an actionable state, but spec'ing metadata, and linked data, is not my strongest suit, so please prod with questions

**Comment by mjgiarlo** [comment]
Thanks, @hannahfrost! I think hooking up to a remote vocabulary like VIAF will be useful here, though I'm guessing we'll also need to allow strings since many of the people using HyBox won't have VIAF URIs (or, perhaps, any URI) representing them?

**Comment by hannahfrost** [comment]
You're right of course @mjgiarlo. Maybe someday people and organizations will be issued a URI with their SSN/tax ID; until then, string :)

**Comment by mjgiarlo** [comment]
@hannahfrost Ha!

**Comment by mjgiarlo** [comment]
Oh, one last question! @hannahfrost Which entities should have this field?

- [ ] Works (and other content types when created)
- [ ] Admin Sets
- [ ] (User) Collections
- [ ] FileSets

**Comment by hannahfrost** [comment]
Let's star with Works, @mjgiarlo, as you suggested elsewhere.
