### ISSUE TITLE
Why is there a "log in" link on the create account page?

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyku#340]
On this page: https://nacho.demo.hydrainabox.org/users/sign_up

<img width="1096" alt="screen shot 2016-09-07 at 9 51 47 pm" src="https://cloud.githubusercontent.com/assets/92044/18335492/5a7c725a-7545-11e6-905c-e53091f643e4.png">

**Comment by orangewolf** [comment]
fixed sometime between then and now
