### ISSUE TITLE
Define how Image-type works should behave

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyku#487]
Hyku currently has two work types: GenericWorks and Images. The latter is exactly the same as the former but with a different label -- put otherwise, adding Image as a new work type isn't adding as much value as it could. Generating this new Image type opens up the possibility to have it behave different from our GenericWork type, e.g., Image-specific descriptive metadata and structural metadata (should every Image allow 0-to-many child Images to be attached to it?). This ticket is for defining how Images should be different from GenericWorks.

**Comment by mjgiarlo** [comment]
Assuming @hannahfrost and @anarchivist will take the first pass at this one.

**Comment by mjgiarlo** [comment]
@hannahfrost @anarchivist Should this be in the Ready or In Progress column?

**Comment by anarchivist** [comment]
I think this is still in "Ready."

**Comment by hannahfrost** [comment]
@anarchivist @mjgiarlo @ggeisler  I'm developing ideas here : https://docs.google.com/a/stanford.edu/document/d/19qXX4Yr17cqXSHrnSyknFYqPx1kqoBU_y36UrWN1YO4/edit?usp=sharing

**Comment by anarchivist** [comment]
Added some (late) feedback. Happy to discuss further!

**Comment by mjgiarlo** [comment]
I believe this is now defined and has been broken into new tickets. Closing. (OK, @hannahfrost?)
