### ISSUE TITLE
UI customization: header logo

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyku#488]
As a repository admin, I need to add a logo (representing my institution, department, product, etc.) to the navbar header via the settings UI, so that I can easily customize the look of my repository.

Use CarrierWave for this, and specify appropriate file dimensions/formats.

**Comment by ggeisler** [comment]
@mjgiarlo Do you have any specific requests or use cases that would argue for specific placement of the logo? Specifically, whether in the small top bar (e.g., where the rosette is at the very top left in the screenshot below) versus in the main masthead area (the larger section with the image background)?

Or is the requirement just the option of putting the logo somewhere in the general header area?

![stanford_digital_repository____online_deposit](https://cloud.githubusercontent.com/assets/101482/20573554/9328fae2-b16d-11e6-811b-a721dfb3353c.png)

**Comment by mjgiarlo** [comment]
@ggeisler No specific requests, no. I defer to your good sensibilities!
