### ISSUE TITLE
Introduce a new repository role: Administrative Set Administrator

### ISSUE THREAD

**Issue by hannahfrost** [samvera/hyku#497]
The Administrative Set Administrator is able to:
- create admin sets
- delete admin sets
- manage admin set users

Unlike a Repository Administrator, the Administrative Set Administrator is NOT able to:
- configure repository settings
- configure repository users
- create/delete user collections

See: https://docs.google.com/spreadsheets/d/1TSZ8CUuq6puwzyJ1Av0aQ798FOQZgzhkn2jaDYyt118/edit#gid=0

**Comment by hannahfrost** [comment]
@mjgiarlo @jcoyne @ggeisler Let's discuss these role permissions and when is a good time to introduce them. hashtag maybenotMVP

**Comment by ggeisler** [comment]
@hannahfrost Isn't the title for this role actually "Administrative Set Administrator"? This would be the global, repository-wide role.

And the "Administrative Set Manager" is the admin set specific role?

That would be aligned with your permissions matrix (and my updated manage users mockup).

**Comment by hannahfrost** [comment]
@ggeisler Yes, you are right. I've updated the ticket title to reflect the name change per our discussion last week.
