### ISSUE TITLE
Cron job to run the rake task to prune guest users

### ISSUE THREAD

**Issue by jcoyne** [samvera/hyku#606]
https://github.com/cbeer/devise-guests/blob/master/lib/railties/devise_guests.rake#L2-L5

**Comment by jeremyf** [comment]
I'm wondering if it makes sense to add the Whenever gem to help with crontab management?

https://rubygems.org/gems/whenever

**Comment by atz** [comment]
Something like `whenever` might be useful, but the task can certainly be written without it.

**Comment by atz** [comment]
@jcoyne so the devise-guests job already exists and hyku has access to it.  What is left to do?  Is this really a problem for our AWS config repo?  Or do we have to repackage that task somehow for other hyku consumers?

**Comment by jcoyne** [comment]
We just need to create a cron entry (or the equivalent for AWS)

**Comment by atz** [comment]
@jcoyne so this is a problem for our AWS repo, not hyku?

**Comment by mjgiarlo** [comment]
@atz Yup.
